### ISSUE TITLE
Non-root (e.g. HPC) installation exploration

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#177] opened 2019-09-14 18:14 UTC
This seems to be trivial with miniconda (thx @effigies for the hint, and @yarikoptic  for putting the pieces into conda). Here is the recipe:

```sh
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash Miniconda3-latest-Linux-x86_64.sh
# acknowledge license, keep everything at default
$ conda install -c conda-forge datalad

# result
$ datalad --version
datalad 0.11.7
$ git-annex version
git-annex version: 7.20190819-ge4cecf8
...
$ git --version
git version 2.20.1

# fully populated conda installation
$ du -sh miniconda3/
856M    miniconda3/
```

The installer automatically configures the shell to make conda-installed tools accessible, so no further configuration is necessary. Such a snippet is added to `.bashrc` (all paths, here and below, have been redacted):

```
...
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

The installed datalad version is not suitable for the handbook yet, but 0.12 is coming.

@dickscheid this approach should avoid tedious hand-deployment, give immediate accessibility with requiring per-dataset reconfiguration, and also offers built-in update-ability. Proper functioning verified on a JURECA login node (minus two failing tests, see below).

```
$ datalad test      
[INFO   ] Starting test run for module(s): ['datalad'] 
Running unit tests for datalad
Python version 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
nose version 1.3.7
...
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_files_split_exc(<class 'datalad.support.annexrepo.AnnexRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/HOME/miniconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/HOME/miniconda3/lib/python3.7/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 2575, in check_files_split_exc
    r.add(files)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 321, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1527, in add
    git_options=git_options, annex_options=annex_options, update=update
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1602, in add_
    for rec in to_be_added_recs
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1600, in <dictcomp>
    expected_additions = {
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1572, in _get_to_be_added_recs
    files, git_options=_git_options, update=update):
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 1150, in add_
    to_options(update=update) + ['--verbose']
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1310, in _git_custom_command
    return super(AnnexRepo, self)._git_custom_command(*args, **kwargs)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 321, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 1809, in _git_custom_command
    expect_fail=expect_fail)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 1846, in _run_command_files_split
    *args, **kwargs)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/cmd.py", line 697, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/cmd.py", line 506, in run
    stdin=stdin)
  File "//HOME/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "//HOME/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'git'

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_files_split_exc(<class 'datalad.support.gitrepo.GitRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//HOME/miniconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "//HOME/miniconda3/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 2579, in check_files_split_exc
    assert_not_in('too long', str(ecm.exception))
AssertionError: 'too long' unexpectedly found in "[Errno 7] Argument list too long: 'git'"

----------------------------------------------------------------------
Ran 905 tests in 1009.025s

FAILED (SKIP=105, errors=1, failures=1)
```

And git-annex tests are happy too, but when ran in my HOME at some point exceeded the disk quotas. Running in `/tmp/` avoided this problem:

```
$ git annex test
...
All 366 tests passed (675.81s)
```

@adswa I think we can just add this to the list of installation options (a linux system, where there is no root access), and refer to it in the course.

@bpoldrack can you have a look at the test failure on jureca? Those might simply be us still making inappropriate assumptions on what is possible. thx!

**Comment by yarikoptic** [comment] 2019-09-14 18:24
Note that conda doesn't have git-annex for osx or windows yet. So in those systems git annex should be installed separately first. But datalad and datalad-container should be available via conda

**Comment by yarikoptic** [comment] 2019-09-14 18:48
Regarding pre releases https://github.com/datalad/datalad/issues/3676

**Comment by adswa** [comment] 2019-09-14 18:57
Awesome, thx! I'll add it to the installation section.

**Comment by effigies** [comment] 2019-09-14 19:02
As noted in https://github.com/datalad/datalad/issues/3676#issuecomment-531504919, upgrading to a version available on PyPI works just as expected in conda environments. Conda is very good about keeping its index in order when the same package is upgraded from a pip-installed version to a conda-installed version and vice-versa.

**Comment by bpoldrack** [comment] 2019-09-16 10:40
FTR: Installation recipe confirmed, with one exception: If I do it that way, `nose` is missing. Apart from that - works.

Re datalad-test:
Looking into it, @mih.
Ran it first on /tmp:

```
Ran 905 tests in 1194.053s

FAILED (SKIP=105, errors=2, failures=3)
```

So, there's more. Currently running from within my home. Will then have a closer look at the failures/errors.

**Comment by bpoldrack** [comment] 2019-09-16 12:38
@mih: Can you confirm that on your setup on JURECA annex v5 is still default? Because the two additional failures, that I have, seem to be caused by the switch to v7.

**Comment by mih** [comment] 2019-09-16 12:50
Yes, if i `create` a dataset I get:

```
$ git annex version
git-annex version: 7.20190819-ge4cecf8
build flags: Assistant Webapp Pairing S3 WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.21.1 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.3 feed-1.0.1.0 ghc-8.6.5 http-client-0.5.14 persistent-sqlite-2.9.3 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: linux x86_64
supported repository versions: 5 7
upgrade supported from repository versions: 0 1 2 3 4 5 6
local repository version: 5
```

So v5, but I cannot confidently say that v7 is not happening inside a `datalad test` run. But if it does, I did not specifically ask for it.

**Comment by bpoldrack** [comment] 2019-09-16 13:15
Re Argument list too long:

In the respective tests, the inflated calls are not chunked at all. Seems like this suspiciously high number is responsible for it:

```python
>>> os.sysconf('SC_ARG_MAX')
4611686018427387903
```

**Comment by bpoldrack** [comment] 2019-09-16 13:58
So, conclusion from looking into those errors, @mih: Limited "real" concern regarding datalad working on that box: 

- Two tests fail to properly test for the correct thing on new annex (not a real problem, and as far as I remember @kyleam addressed this recently. Was that in master only, @kyleam ?

- the testing for chunking oversized calls is failing, because that chunking doesn't work indeed. We can workaround the latter the same way @yarikoptic did for python 3.4, although that is somewhat fragile until we know the real reason `SC_ARG_MAX` is reporting such nonsense ( I mean, look at that value: That's a number that would exceed the memory of the entire freakin planet ;-) )
However, this does need fixing, but it's really only actually failing in the case of hugely artificially blown up calls for testing that exact functionality. No "real" call involved.

- Finally, I got one additional failure where `datalad unlock` claims, that the file is not under annex, yielding "not needed", while a subsequent call to write to that very file fails with permission denied, since it actually is annexed. Looking into that one (guess also v7 related).

**Comment by kyleam** [comment] 2019-09-16 14:24
>  * Two tests fail to properly test for the correct thing on new annex (not a real problem, and as far as I remember @kyleam addressed this recently. Was that in master only, @kyleam ?

Sorry, I haven't been following the discussion and quickly scanning I don't see what these two tests are.  There were two series recently, both on top of 0.11.x, that prepare for upstream changes in git-annex:

  * datalad/datalad#3631 updates our tests to work with a git-annex that does not support direct mode.  This has been merged and is included in 0.11.7.

   * datalad/datalad#3648 updates our tests to work with a git-annex that auto-upgrades v5 to v7.  This series hasn't been merged yet.

**Comment by bpoldrack** [comment] 2019-09-17 06:59
@kyleam: So, #3648 is what this is about. So, I'll not do anything about it until this is merged, I guess.

**Comment by dickscheid** [comment] 2019-09-17 12:20
Installation procedure confirmed here as well on JUDAC, absolutely straightforward. I will now see wether there are issues with existing repositories that had been created on JURECA with different software versions.

**Comment by mih** [comment] 2019-10-16 20:14
This report reminded me that the current instructions in the handbook are missing the fact that conda only has 0.11 right now. We need to add a note on the for the time being. See: https://neurostars.org/t/datalad-install-datalad-containers-extension-in-conjunction-with-singularity-datalad-container/5246

**Comment by adswa** [comment] 2019-10-16 20:17
Will do so right-away. And, in the same vein, will get rid of the the note on a "future release" on the landing page.

**Comment by mih** [comment] 2019-10-16 20:24
Good point! Thx.

**Comment by adswa** [comment] 2019-12-03 15:38
I think can be closed.

**Closed by adswa** 2019-12-03 15:38 UTC
